### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by goshdark138** [datauy/pormibarrio#113]
hola necesito ayuda con el montaje de pormibarrio me podrían colaborar con algunos consejos

**Comment by fernandouval** [comment]
Claro, te dejo mi skype: fernando.uval1

Saludos

**Comment by goshdark138** [comment]
gracias saludos

**Comment by goshdark138** [comment]
@fernandouval hace ratos te envié la invitación de skype, acéptala por favor.
